"use client";

import { useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { CreateChapterDialog } from "@/components/create-chapter-dialog";
import { ArrowLeft, FileText, Calendar, Trash2, Eye, Sparkles, CheckCircle2, RefreshCw, Upload } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { zhCN } from "date-fns/locale";
import { useAlertDialog } from "@/hooks/use-alert-dialog";

type Chapter = {
  id: string;
  chapterNumber: number;
  title: string;
  wordCount: number;
  status: string;
  outlineItemId?: string;
  createdAt: string;
  updatedAt: string;
};

type OutlineItem = {
  id: string;
  title: string;
  summary: string;
  order: number;
  chapterNumber: number; // 实际存储的是幕编号
};

type Act = {
  actNumber: number;
  title: string;
  chapterRange: string; // 如 "第1-50章"
  description: string;
  plotSegments?: any[];
};

type Outline = {
  id: string;
  structure: Act[];
  items: OutlineItem[];
};

export default function ChaptersPage() {
  const { confirm, alert } = useAlertDialog();
  const params = useParams();
  const projectId = params.id as string;

  const [chapters, setChapters] = useState<Chapter[]>([]);
  const [outline, setOutline] = useState<Outline | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [autoGeneratingAct, setAutoGeneratingAct] = useState<number | null>(null);
  const [autoProgress, setAutoProgress] = useState<{ actNumber: number; current: number; total: number } | null>(null);
  const [stopRequestedAct, setStopRequestedAct] = useState<number | null>(null);
  const [publishingChapterId, setPublishingChapterId] = useState<string | null>(null);
  const [selectedChapterIds, setSelectedChapterIds] = useState<Set<string>>(new Set());
  const [isBatchPublishing, setIsBatchPublishing] = useState(false);
  const [batchTaskId, setBatchTaskId] = useState<string | null>(null);
  const [batchSelectCount, setBatchSelectCount] = useState("3");
  const [autoGenerateWordCount, setAutoGenerateWordCount] = useState("2300");
  const [autoGenerateDialogAct, setAutoGenerateDialogAct] = useState<Act | null>(null);
  const [batchProgress, setBatchProgress] = useState<{
    current: number;
    total: number;
    status: string;
    currentChapter: { chapterNumber: number; title: string } | null;
  }>({
    current: 0,
    total: 0,
    status: "idle",
    currentChapter: null,
  });
  const stopRequestedActRef = useRef<number | null>(null);

  useEffect(() => {
    fetchData();
  }, [projectId]);

  useEffect(() => {
    if (!batchTaskId) return;
    let stopped = false;
    const timer = setInterval(async () => {
      if (stopped) return;
      try {
        const res = await fetch(
          `/api/projects/${projectId}/chapters/publish-batch/status?taskId=${encodeURIComponent(batchTaskId)}`
        );
        const data = await res.json().catch(() => ({}));
        if (!res.ok) {
          throw new Error(data.error || "获取批量发布进度失败");
        }
        const task = data.task;
        setBatchProgress({
          current: task.current || 0,
          total: task.total || 0,
          status: task.status || "running",
          currentChapter: task.currentChapter || null,
        });
        const publishedIds: string[] = Array.isArray(task.publishedChapterIds)
          ? task.publishedChapterIds
          : [];
        if (publishedIds.length > 0) {
          setChapters((prev) =>
            prev.map((c) =>
              publishedIds.includes(c.id) ? { ...c, status: "published" } : c
            )
          );
          setSelectedChapterIds((prev) => {
            const next = new Set(prev);
            for (const id of publishedIds) next.delete(id);
            return next;
          });
        }

        if (task.status === "completed") {
          setIsBatchPublishing(false);
          setPublishingChapterId(null);
          setBatchTaskId(null);
          alert(`批量发布完成：${task.successCount || task.current || 0}/${task.total || 0}`, "success");
        } else if (task.status === "failed") {
          setIsBatchPublishing(false);
          setPublishingChapterId(null);
          setBatchTaskId(null);
          alert(
            `批量发布失败：已成功 ${task.successCount || task.current || 0}/${task.total || 0}。${task.error || ""}`,
            "error"
          );
        }
      } catch (error) {
        setIsBatchPublishing(false);
        setBatchTaskId(null);
        alert(error instanceof Error ? error.message : "获取批量发布进度失败", "error");
      }
    }, 1200);
    return () => {
      stopped = true;
      clearInterval(timer);
    };
  }, [batchTaskId, projectId, alert]);

  const fetchData = async () => {
    try {
      // 获取章节列表
      const chaptersRes = await fetch(`/api/projects/${projectId}/chapters`);
      if (chaptersRes.ok) {
        const data = await chaptersRes.json();
        setChapters(data.chapters);
      }

      // 获取大纲
      const outlineRes = await fetch(`/api/projects/${projectId}/outline`);
      if (outlineRes.ok) {
        const data = await outlineRes.json();
        if (data.outline) {
          setOutline(data.outline);
        }
      }
    } catch (error) {
      console.error("获取数据失败:", error);
    } finally {
      setIsLoading(false);
    }
  };

  // 解析章节范围，如 "第1-50章" -> { start: 1, end: 50, count: 50 }
  const parseChapterRange = (range: string) => {
    const match = range.match(/第(\d+)-(\d+)章/);
    if (match) {
      const start = parseInt(match[1]);
      const end = parseInt(match[2]);
      return { start, end, count: end - start + 1 };
    }
    return { start: 0, end: 0, count: 0 };
  };

  // 获取某个幕中已生成的章节
  const getActChapters = (actNumber: number) => {
    const act = outline?.structure.find(a => a.actNumber === actNumber);
    if (!act) return [];

    const range = parseChapterRange(act.chapterRange);
    return chapters.filter(c =>
      c.chapterNumber >= range.start && c.chapterNumber <= range.end
    ).sort((a, b) => a.chapterNumber - b.chapterNumber);
  };

  // 获取某个幕的下一个待生成章节号
  const getNextChapterNumber = (actNumber: number) => {
    const act = outline?.structure.find(a => a.actNumber === actNumber);
    if (!act) return null;

    const range = parseChapterRange(act.chapterRange);
    const actChapters = getActChapters(actNumber);

    if (actChapters.length === 0) {
      return range.start; // 返回该幕的第一章
    }

    const lastChapter = actChapters[actChapters.length - 1];
    if (lastChapter.chapterNumber < range.end) {
      return lastChapter.chapterNumber + 1;
    }

    return null; // 该幕所有章节已生成
  };

  const handleDelete = async (chapterId: string) => {
    if (!await confirm({ title: "确认删除", description: "确定要删除这个章节吗？此操作不可恢复。", type: "warning" })) {
      return;
    }

    try {
      const response = await fetch(
        `/api/projects/${projectId}/chapters/${chapterId}`,
        { method: "DELETE" }
      );

      if (response.ok) {
        setChapters(chapters.filter((c) => c.id !== chapterId));
      }
    } catch (error) {
      console.error("删除章节失败:", error);
    }
  };

  const handleAutoGenerateAct = async (act: Act) => {
    if (autoGeneratingAct !== null) return;
    const parsedWordCount = Number.parseInt(autoGenerateWordCount, 10);
    if (!Number.isFinite(parsedWordCount) || parsedWordCount < 1000 || parsedWordCount > 5000) {
      alert("自动生成本幕的目标字数需在 1000-5000 之间", "warning");
      return;
    }

    const range = parseChapterRange(act.chapterRange);
    const existing = new Set(getActChapters(act.actNumber).map((c) => c.chapterNumber));
    const pendingChapterNumbers: number[] = [];
    for (let n = range.start; n <= range.end; n++) {
      if (!existing.has(n)) pendingChapterNumbers.push(n);
    }

    if (pendingChapterNumbers.length === 0) {
      alert(`第 ${act.actNumber} 幕已全部生成完成`, "success");
      return;
    }

    setAutoGeneratingAct(act.actNumber);
    setStopRequestedAct(null);
    stopRequestedActRef.current = null;
    setAutoProgress({ actNumber: act.actNumber, current: 0, total: pendingChapterNumbers.length });

    let successCount = 0;
    const maxRetries = 2;
    const retryDelayMs = 60_000;
    try {
      for (let i = 0; i < pendingChapterNumbers.length; i++) {
        if (stopRequestedActRef.current === act.actNumber) {
          break;
        }
        const chapterNumber = pendingChapterNumbers[i];
        setAutoProgress({
          actNumber: act.actNumber,
          current: i + 1,
          total: pendingChapterNumbers.length,
        });

        let result: any = null;
        let attempt = 0;
        while (attempt <= maxRetries) {
          if (stopRequestedActRef.current === act.actNumber) {
            break;
          }
          attempt += 1;
          const response = await fetch(`/api/projects/${projectId}/chapters`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              actNumber: act.actNumber,
              chapterNumber,
              wordCount: parsedWordCount,
              versionCount: 1,
              autoSelectBest: false,
              scoreThreshold: 70,
            }),
          });

          if (response.ok) {
            result = await response.json().catch(() => null);
            break;
          }

          const errorResult = await response.json().catch(() => ({}));
          const errorMessage = errorResult.error || `第 ${chapterNumber} 章生成失败`;
          if (attempt > maxRetries) {
            throw new Error(`${errorMessage}（已重试 ${maxRetries} 次）`);
          }

          alert(
            `第 ${chapterNumber} 章生成失败，60 秒后进行第 ${attempt} 次重试`,
            "warning"
          );
          await new Promise((resolve) => setTimeout(resolve, retryDelayMs));
        }

        if (stopRequestedActRef.current === act.actNumber) {
          break;
        }
        if (!result?.chapter) {
          await fetchData();
          throw new Error(`第 ${chapterNumber} 章生成失败（响应异常）`);
        }

        if (result?.chapter) {
          setChapters((prev) => {
            const exists = prev.some((c) => c.id === result.chapter.id);
            if (exists) return prev;
            return [...prev, result.chapter].sort((a, b) => a.chapterNumber - b.chapterNumber);
          });
        }
        successCount += 1;
      }

      if (stopRequestedActRef.current === act.actNumber) {
        alert(`已停止自动生成：本次成功生成 ${successCount} 章`, "success");
      } else {
        alert(`第 ${act.actNumber} 幕自动生成完成，成功生成 ${successCount} 章`, "success");
      }
      await fetchData();
    } catch (error) {
      alert(
        `自动生成中断：已成功 ${successCount} 章。${error instanceof Error ? error.message : "请稍后重试"}`,
        "error"
      );
      await fetchData();
    } finally {
      setAutoGeneratingAct(null);
      setAutoProgress(null);
      setStopRequestedAct(null);
      stopRequestedActRef.current = null;
    }
  };

  const getPendingChapterNumbers = (act: Act): number[] => {
    const range = parseChapterRange(act.chapterRange);
    const existing = new Set(getActChapters(act.actNumber).map((c) => c.chapterNumber));
    const pendingChapterNumbers: number[] = [];
    for (let n = range.start; n <= range.end; n++) {
      if (!existing.has(n)) pendingChapterNumbers.push(n);
    }
    return pendingChapterNumbers;
  };

  const openAutoGenerateDialog = (act: Act) => {
    if (autoGeneratingAct !== null) return;
    const pending = getPendingChapterNumbers(act);
    if (pending.length === 0) {
      alert(`第 ${act.actNumber} 幕已全部生成完成`, "success");
      return;
    }
    setAutoGenerateDialogAct(act);
  };

  const confirmAutoGenerate = async () => {
    if (!autoGenerateDialogAct) return;
    const targetAct = autoGenerateDialogAct;
    setAutoGenerateDialogAct(null);
    await handleAutoGenerateAct(targetAct);
  };

  const handleStopAutoGenerate = (actNumber: number) => {
    if (autoGeneratingAct !== actNumber) return;
    setStopRequestedAct(actNumber);
    stopRequestedActRef.current = actNumber;
  };

  const isOutlineItemGenerated = (outlineItemId: string) => {
    return chapters.some(c => c.outlineItemId === outlineItemId);
  };

  const getStatusText = (status: string) => {
    const statusMap: Record<string, string> = {
      draft: "草稿",
      published: "已发布",
    };
    return statusMap[status] || "草稿";
  };

  const getStatusVariant = (status: string) => {
    const variantMap: Record<string, "default" | "secondary" | "outline"> = {
      draft: "secondary",
      published: "outline",
    };
    return variantMap[status] || "secondary";
  };

  const handlePublish = async (chapter: Chapter) => {
    if (chapter.status === "published") {
      alert("该章节已发布", "success");
      return;
    }
    setPublishingChapterId(chapter.id);
    try {
      const res = await fetch(
        `/api/projects/${projectId}/chapters/${chapter.id}/publish`,
        { method: "POST" }
      );
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(data.error || "发布失败");
      }
      setChapters((prev) =>
        prev.map((c) =>
          c.id === chapter.id ? { ...c, status: "published" } : c
        )
      );
      setSelectedChapterIds((prev) => {
        const next = new Set(prev);
        next.delete(chapter.id);
        return next;
      });
      alert("章节已发布到番茄", "success");
    } catch (error) {
      alert(error instanceof Error ? error.message : "发布失败", "error");
    } finally {
      setPublishingChapterId(null);
    }
  };

  const toggleSelectChapter = (chapterId: string, checked: boolean) => {
    setSelectedChapterIds((prev) => {
      const next = new Set(prev);
      if (checked) next.add(chapterId);
      else next.delete(chapterId);
      return next;
    });
  };

  const selectNextUnpublishedChapters = () => {
    const count = Math.max(1, Number.parseInt(batchSelectCount, 10) || 3);
    const unpublished = [...chapters]
      .filter((c) => c.status !== "published")
      .sort((a, b) => a.chapterNumber - b.chapterNumber)
      .slice(0, count);
    setSelectedChapterIds(new Set(unpublished.map((c) => c.id)));
  };

  const handleBatchPublish = async () => {
    if (isBatchPublishing || selectedChapterIds.size === 0) return;
    const selected = chapters
      .filter((c) => selectedChapterIds.has(c.id) && c.status !== "published")
      .sort((a, b) => a.chapterNumber - b.chapterNumber);
    if (selected.length === 0) {
      alert("选中的章节均已发布", "success");
      return;
    }

    const ok = await confirm({
      title: "确认批量发布",
      description: `将按章节顺序发布 ${selected.length} 章（第 ${selected[0].chapterNumber} 章到第 ${selected[selected.length - 1].chapterNumber} 章）。`,
      type: "warning",
    });
    if (!ok) return;

    setIsBatchPublishing(true);
    try {
      const res = await fetch(
        `/api/projects/${projectId}/chapters/publish-batch`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ chapterIds: selected.map((c) => c.id) }),
        }
      );
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(data.error || "批量发布失败");
      }
      if (!data.taskId) {
        setIsBatchPublishing(false);
        alert(data.message || "所选章节均已发布", "success");
        return;
      }
      setBatchTaskId(data.taskId);
      setBatchProgress({
        current: 0,
        total: data.total || selected.length,
        status: "running",
        currentChapter: null,
      });
    } catch (error) {
      alert(error instanceof Error ? error.message : "批量发布失败", "error");
      setIsBatchPublishing(false);
    }
  };

  // 根据章节号找到所属的幕
  const getActForChapter = (chapterNumber: number) => {
    if (!outline) return null;
    for (const act of outline.structure) {
      const range = parseChapterRange(act.chapterRange);
      if (chapterNumber >= range.start && chapterNumber <= range.end) {
        return act;
      }
    }
    return null;
  };

  const recentChapters = [...chapters]
    .sort((a, b) => b.chapterNumber - a.chapterNumber)
    .slice(0, 3);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <p className="text-muted-foreground">加载中...</p>
      </div>
    );
  }

  return (
    <div>
      <Button variant="ghost" asChild className="mb-4">
        <Link href={`/projects/${projectId}`}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          返回项目
        </Link>
      </Button>

      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-3xl font-bold">章节管理</h1>
          <p className="text-muted-foreground mt-1">
            根据大纲生成章节内容
          </p>
        </div>
      </div>

      <Dialog open={isBatchPublishing}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>批量发布进行中</DialogTitle>
            <DialogDescription>
              请勿关闭页面，系统正在按章节顺序发布。
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            <div className="flex justify-between text-sm text-muted-foreground">
              <span>发布进度</span>
              <span>
                {batchProgress.current}/{batchProgress.total}
              </span>
            </div>
            <div className="w-full bg-secondary rounded-full h-2">
              <div
                className="bg-primary rounded-full h-2 transition-all"
                style={{
                  width:
                    batchProgress.total > 0
                      ? `${(batchProgress.current / batchProgress.total) * 100}%`
                      : "0%",
                }}
              />
            </div>
            <p className="text-sm text-muted-foreground min-h-5">
              {batchProgress.currentChapter
                ? `当前正在发布：第 ${batchProgress.currentChapter.chapterNumber} 章《${batchProgress.currentChapter.title}》`
                : "正在准备下一章发布..."}
            </p>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog
        open={!!autoGenerateDialogAct}
        onOpenChange={(open) => {
          if (!open) setAutoGenerateDialogAct(null);
        }}
      >
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>自动生成本幕</DialogTitle>
            <DialogDescription>
              {autoGenerateDialogAct
                ? `第 ${autoGenerateDialogAct.actNumber} 幕《${autoGenerateDialogAct.title}》将按顺序自动生成剩余章节。`
                : ""}
            </DialogDescription>
          </DialogHeader>
          {autoGenerateDialogAct && (
            <div className="space-y-4">
              <div className="text-sm text-muted-foreground">
                剩余待生成：
                {(() => {
                  const pending = getPendingChapterNumbers(autoGenerateDialogAct);
                  if (pending.length === 0) return "无";
                  return `共 ${pending.length} 章（第 ${pending[0]} 章到第 ${pending[pending.length - 1]} 章）`;
                })()}
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">目标字数（每章）</label>
                <Input
                  type="number"
                  min={1000}
                  max={5000}
                  step={100}
                  value={autoGenerateWordCount}
                  onChange={(e) => setAutoGenerateWordCount(e.target.value)}
                  disabled={autoGeneratingAct !== null}
                />
                <p className="text-xs text-muted-foreground">
                  建议 1500-3000 字，实际生成字数可能有偏差
                </p>
              </div>
              <div className="flex justify-end gap-2">
                <Button
                  variant="outline"
                  onClick={() => setAutoGenerateDialogAct(null)}
                  disabled={autoGeneratingAct !== null}
                >
                  取消
                </Button>
                <Button onClick={confirmAutoGenerate} disabled={autoGeneratingAct !== null}>
                  开始自动生成
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>


      {chapters.length > 0 && (
        <Card className="mb-6">
          <CardContent className="py-4 flex items-center justify-between gap-3">
            <div className="flex-1">
              <p className="text-sm text-muted-foreground">
                已选择 {selectedChapterIds.size} 章（发布时将自动按章节顺序执行）
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Select
                value={batchSelectCount}
                onValueChange={setBatchSelectCount}
                disabled={isBatchPublishing}
              >
                <SelectTrigger className="w-[130px] h-8">
                  <SelectValue placeholder="选择章节数" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1 章</SelectItem>
                  <SelectItem value="3">3 章</SelectItem>
                  <SelectItem value="5">5 章</SelectItem>
                  <SelectItem value="10">10 章</SelectItem>
                </SelectContent>
              </Select>
              <Button
                variant="outline"
                size="sm"
                onClick={selectNextUnpublishedChapters}
                disabled={isBatchPublishing}
              >
                按顺序选择
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setSelectedChapterIds(new Set())}
                disabled={selectedChapterIds.size === 0 || isBatchPublishing}
              >
                清空选择
              </Button>
              <Button
                size="sm"
                onClick={handleBatchPublish}
                disabled={selectedChapterIds.size === 0 || isBatchPublishing}
              >
                {isBatchPublishing ? "批量发布中..." : "发布选中"}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {!outline || outline.structure.length === 0 ? (
        <Card className="text-center py-12">
          <CardContent>
            <FileText className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">还没有大纲</h3>
            <p className="text-muted-foreground mb-4">
              请先创建大纲，然后根据大纲生成章节
            </p>
            <Button asChild>
              <Link href={`/projects/${projectId}/outline`}>
                前往创建大纲
              </Link>
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6">
          {outline.structure.map((act) => {
            const range = parseChapterRange(act.chapterRange);
            const actChapters = getActChapters(act.actNumber);
            const nextChapter = getNextChapterNumber(act.actNumber);
            const progress = range.count > 0 ? (actChapters.length / range.count) * 100 : 0;
            const existingNums = actChapters.map((c) => c.chapterNumber);
            const hasUngenerated = actChapters.length < range.count;

            return (
              <Card key={act.actNumber}>
                <CardHeader>
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-3 mb-2">
                        <Badge variant="default" className="text-base px-3 py-1">
                          第 {act.actNumber} 幕
                        </Badge>
                        <div className="flex flex-col">
                          <Badge variant="outline" className="text-sm w-fit">
                            {act.chapterRange} ({range.count} 章)
                          </Badge>
                          <span className="text-xs text-muted-foreground mt-1">
                            已生成 {actChapters.length}/{range.count}
                          </span>
                        </div>
                      </div>
                      <CardTitle className="text-xl mb-2">{act.title}</CardTitle>
                    </div>
                    {hasUngenerated && (
                      <div className="flex items-center gap-2 shrink-0">
                        <CreateChapterDialog
                          projectId={projectId}
                          actNumber={act.actNumber}
                          chapterNumber={nextChapter || range.start}
                          chapterStart={range.start}
                          chapterEnd={range.end}
                          existingChapterNumbers={existingNums}
                          actTitle={act.title}
                          actDescription={act.description}
                          onSuccess={fetchData}
                          trigger={
                            <Button disabled={autoGeneratingAct !== null}>
                              <Sparkles className="mr-2 h-4 w-4" />
                              生成章节
                            </Button>
                          }
                        />
                        <Button
                          variant="outline"
                          onClick={() => openAutoGenerateDialog(act)}
                          disabled={autoGeneratingAct !== null}
                        >
                          <RefreshCw
                            className={`mr-2 h-4 w-4 ${autoGeneratingAct === act.actNumber ? "animate-spin" : ""}`}
                          />
                          {autoGeneratingAct === act.actNumber && autoProgress
                            ? stopRequestedAct === act.actNumber
                              ? `等待当前任务完成后停止 (${autoProgress.current}/${autoProgress.total})`
                              : `自动生成中 (${autoProgress.current}/${autoProgress.total})`
                            : "自动生成本幕"}
                        </Button>
                        {autoGeneratingAct === act.actNumber && (
                          <Button
                            variant="destructive"
                            onClick={() => handleStopAutoGenerate(act.actNumber)}
                            disabled={stopRequestedAct === act.actNumber}
                          >
                            {stopRequestedAct === act.actNumber ? "等待停止中..." : "停止"}
                          </Button>
                        )}
                      </div>
                    )}
                    {!hasUngenerated && actChapters.length > 0 && (
                      <Badge variant="default" className="gap-1 h-fit shrink-0">
                        <CheckCircle2 className="h-4 w-4" />
                        已完成
                      </Badge>
                    )}
                  </div>
                  <CardDescription className="w-full">{act.description}</CardDescription>
                  {range.count > 0 && (
                    <div className="mt-4">
                      <div className="flex justify-between text-sm text-muted-foreground mb-1">
                        <span>进度</span>
                        <span>{progress.toFixed(0)}%</span>
                      </div>
                      <div className="w-full bg-secondary rounded-full h-2">
                        <div
                          className="bg-primary rounded-full h-2 transition-all"
                          style={{ width: `${progress}%` }}
                        />
                      </div>
                    </div>
                  )}
                </CardHeader>
                {actChapters.length > 0 && (
                  <CardContent>
                    <div className="space-y-2">
                      <h4 className="text-sm font-semibold mb-3">已生成章节</h4>
                      <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                        {actChapters.map((chapter) => (
                          <div
                            key={chapter.id}
                            className="flex items-center gap-2 p-2 border rounded hover:bg-accent transition-colors group"
                          >
                            <Checkbox
                              checked={selectedChapterIds.has(chapter.id)}
                              disabled={chapter.status === "published" || isBatchPublishing}
                              onCheckedChange={(checked) =>
                                toggleSelectChapter(chapter.id, checked === true)
                              }
                            />
                            <Link
                              href={`/projects/${projectId}/chapters/${chapter.id}`}
                              className="flex items-center gap-2 flex-1 min-w-0"
                            >
                              <FileText className="h-4 w-4 text-muted-foreground shrink-0" />
                              <div className="flex-1 min-w-0">
                                <p className="text-sm font-medium truncate">
                                  第 {chapter.chapterNumber} 章
                                </p>
                                <p className="text-xs text-muted-foreground truncate">
                                  {chapter.title}
                                </p>
                                <p className="text-xs text-muted-foreground">
                                  {chapter.wordCount.toLocaleString()} 字
                                </p>
                                {chapter.status === "published" && (
                                  <p className="text-xs text-green-600">已发布</p>
                                )}
                              </div>
                            </Link>
                            <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity shrink-0">
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-6 w-6 text-green-600 hover:text-green-600"
                                disabled={publishingChapterId === chapter.id || chapter.status === "published"}
                                onClick={(e) => {
                                  e.preventDefault();
                                  handlePublish(chapter);
                                }}
                                title={chapter.status === "published" ? "已发布" : "发布"}
                              >
                                <Upload className={`h-3 w-3 ${publishingChapterId === chapter.id ? "animate-pulse" : ""}`} />
                              </Button>
                              <CreateChapterDialog
                                projectId={projectId}
                                actNumber={act.actNumber}
                                chapterNumber={chapter.chapterNumber}
                                actTitle={act.title}
                                actDescription={act.description}
                                onSuccess={fetchData}
                                regenerate={{
                                  chapterId: chapter.id,
                                  chapterTitle: chapter.title,
                                }}
                                trigger={
                                  <Button
                                    variant="ghost"
                                    size="icon"
                                    className="h-6 w-6"
                                  >
                                    <RefreshCw className="h-3 w-3" />
                                  </Button>
                                }
                              />
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-6 w-6 text-destructive hover:text-destructive"
                                onClick={(e) => {
                                  e.preventDefault();
                                  handleDelete(chapter.id);
                                }}
                              >
                                <Trash2 className="h-3 w-3" />
                              </Button>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </CardContent>
                )}
              </Card>
            );
          })}

          {chapters.length > 0 && (
            <>
              <div className="flex items-center justify-between mt-8 mb-4">
                <h2 className="text-2xl font-bold">已生成章节</h2>
                <Button asChild variant="outline" size="sm">
                  <Link href={`/projects/${projectId}/chapters/all`}>查看全部</Link>
                </Button>
              </div>
              <div className="space-y-4">
                {recentChapters.map((chapter) => (
                  <Card key={chapter.id} className="hover:shadow-md transition-shadow">
                    <CardHeader>
                      <div className="flex justify-between items-start">
                        <div className="flex-1">
                          <div className="flex items-center gap-3 mb-2">
                            <Badge variant="outline">
                              第 {chapter.chapterNumber} 章
                            </Badge>
                            <Badge
                              variant={getStatusVariant(chapter.status)}
                              className={
                                chapter.status === "published"
                                  ? "border-green-600 text-green-600"
                                  : undefined
                              }
                            >
                              {getStatusText(chapter.status)}
                            </Badge>
                          </div>
                          <CardTitle className="text-xl">{chapter.title}</CardTitle>
                          <CardDescription className="mt-2 flex items-center gap-4">
                            <span className="flex items-center gap-1">
                              <FileText className="h-4 w-4" />
                              {chapter.wordCount.toLocaleString()} 字
                            </span>
                            <span className="flex items-center gap-1">
                              <Calendar className="h-4 w-4" />
                              {formatDistanceToNow(new Date(chapter.updatedAt), {
                                addSuffix: true,
                                locale: zhCN,
                              })}
                            </span>
                          </CardDescription>
                        </div>
                        <div className="flex gap-2">
                          <Button asChild variant="outline" size="sm">
                            <Link href={`/projects/${projectId}/chapters/${chapter.id}`}>
                              <Eye className="mr-2 h-4 w-4" />
                              查看
                            </Link>
                          </Button>
                          {(() => {
                            const act = getActForChapter(chapter.chapterNumber);
                            if (!act) return null;
                            return (
                              <CreateChapterDialog
                                projectId={projectId}
                                actNumber={act.actNumber}
                                chapterNumber={chapter.chapterNumber}
                                actTitle={act.title}
                                actDescription={act.description}
                                onSuccess={fetchData}
                                regenerate={{
                                  chapterId: chapter.id,
                                  chapterTitle: chapter.title,
                                }}
                                trigger={
                                  <Button variant="outline" size="sm">
                                    <RefreshCw className="mr-2 h-4 w-4" />
                                    重新生成
                                  </Button>
                                }
                              />
                            );
                          })()}
                          <Button
                            variant={chapter.status === "published" ? "outline" : "default"}
                            size="sm"
                            disabled={publishingChapterId === chapter.id || chapter.status === "published"}
                            onClick={() => handlePublish(chapter)}
                          >
                            <Upload className={`mr-2 h-4 w-4 ${publishingChapterId === chapter.id ? "animate-pulse" : ""}`} />
                            {chapter.status === "published" ? "已发布" : (publishingChapterId === chapter.id ? "发布中..." : "发布")}
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleDelete(chapter.id)}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardHeader>
                  </Card>
                ))}
              </div>
            </>
          )}

          {chapters.length > 0 && (
            <Card className="mt-6">
              <CardHeader>
                <CardTitle>统计信息</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground">章节总数</p>
                    <p className="text-2xl font-bold">{chapters.length}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">总字数</p>
                    <p className="text-2xl font-bold">
                      {chapters.reduce((sum, c) => sum + c.wordCount, 0).toLocaleString()}
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">平均字数</p>
                    <p className="text-2xl font-bold">
                      {Math.round(
                        chapters.reduce((sum, c) => sum + c.wordCount, 0) / chapters.length
                      ).toLocaleString()}
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">已发布</p>
                    <p className="text-2xl font-bold">
                      {chapters.filter((c) => c.status === "published").length}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      )}
    </div>
  );
}
